### PR TITLE
Added workflows for autocommenting on issue creation, PR Raised and Merged

### LINKED ISSUE #59: Actions: Multiple automation
# Actions: Multiple automation

#### Job:
- [ ] Auto Commenting Feat for Issue Creation
- [ ] Auto Commenting feature for PR Merged
- [ ] Auto Commenting feature for PR Raised

- [x] Valid
- [x] Assigned
- [ ] PR Generated
- [ ] Verified and Merged
- [ ] Dispose

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #59 

@iHRex please review this PR and merge it if it is good to go

### CODE REVIEW

**Comment by Asymtode712** [comment]
@iHRex please add 'gssoc' and 'level' labels

**Comment by iHRex** [comment]
The 'gssoc' label is already mentioned. This issue doesn't quantify for any level tag.

Thank you!

**Comment by Asymtode712** [comment]
@iHRex how would I get points for this 'gssoc' contribution then

**Comment by iHRex** [comment]
I'd request you to go through the point distribution table.

Thank you!

**Comment by Asymtode712** [comment]
@iHRex I have already gone through it and these workflows comes under level 1 and as I have contributed 3 workflows you should assign me either level 2 or level 3 label

**Comment by Asymtode712** [comment]
SS1
SS2
You can check my recent contributions, I am majorly contributing in Github actions and workflows

**Comment by Asymtode712** [comment]
@iHRex everyone has given a level tag

**Comment by Asymtode712** [comment]
@iHRex Sorry if I bothered you, will try to make another good contribution in your repo, really sorry 🙏

**Pull request merged**
