### PR TITLE
Updating the contribution guidelines in Readme .

### PR DESCRIPTION
**Pull request by Sibam-Paul**
IssueNo : #62

Please inorder to Count this PR in GSSOC please:-

- Kindly first assign me this PR 
- give tags to this PR
     - gssoc 
     - level1 (with small l and without space)
    
Please view my PR

### CODE REVIEW

**Comment by Sibam-Paul** [comment]
@iHRex @apekkshaa please check my PR

**Comment by Sibam-Paul** [comment]
@iHRex Please assign me this PR

**Comment by Sibam-Paul** [comment]
@please give level1 as its not counting in the leaderboard

**Review by iHRex — APPROVED** [review]

**Comment by iHRex** [comment]
@Sibam-Paul 

This doesn't tend to be!

Thank you!

**Comment by Sibam-Paul** [comment]
ok

**Pull request merged**
